create extension if not exists pgcrypto with schema extensions;

create table if not exists public.order_auto_contracts (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  buyer_name text,
  buyer_email text,
  vehicle_name text,
  total_price text,
  status text not null default '下書き',
  document_type text not null default '契約書',
  data jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.order_auto_contracts
  add column if not exists buyer_email text,
  add column if not exists document_type text not null default '契約書',
  add column if not exists completed_at timestamptz;

create table if not exists public.order_auto_remote_contracts (
  id uuid primary key default gen_random_uuid(),
  contract_id text not null references public.order_auto_contracts(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  access_token_hash bytea not null unique,
  passcode_hash text not null,
  contract_data jsonb not null,
  status text not null default '送信済み',
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  expires_at timestamptz not null,
  opened_at timestamptz,
  completed_at timestamptz,
  signer_name text,
  consent_items jsonb not null default '[]'::jsonb,
  signature_data_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_auto_remote_events (
  id bigint generated by default as identity primary key,
  remote_contract_id uuid not null references public.order_auto_remote_contracts(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_order_auto_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists order_auto_contracts_set_updated_at on public.order_auto_contracts;
create trigger order_auto_contracts_set_updated_at
before update on public.order_auto_contracts
for each row execute function public.set_order_auto_updated_at();

drop trigger if exists order_auto_remote_contracts_set_updated_at on public.order_auto_remote_contracts;
create trigger order_auto_remote_contracts_set_updated_at
before update on public.order_auto_remote_contracts
for each row execute function public.set_order_auto_updated_at();

alter table public.order_auto_contracts enable row level security;
alter table public.order_auto_remote_contracts enable row level security;
alter table public.order_auto_remote_events enable row level security;

drop policy if exists "order_auto_contracts_select_own" on public.order_auto_contracts;
drop policy if exists "order_auto_contracts_insert_own" on public.order_auto_contracts;
drop policy if exists "order_auto_contracts_update_own" on public.order_auto_contracts;
drop policy if exists "order_auto_contracts_delete_own" on public.order_auto_contracts;

create policy "order_auto_contracts_select_own"
on public.order_auto_contracts
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "order_auto_contracts_insert_own"
on public.order_auto_contracts
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "order_auto_contracts_update_own"
on public.order_auto_contracts
for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "order_auto_contracts_delete_own"
on public.order_auto_contracts
for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "order_auto_remote_contracts_select_own" on public.order_auto_remote_contracts;
drop policy if exists "order_auto_remote_contracts_delete_own" on public.order_auto_remote_contracts;

create policy "order_auto_remote_contracts_select_own"
on public.order_auto_remote_contracts
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

create policy "order_auto_remote_contracts_delete_own"
on public.order_auto_remote_contracts
for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

drop policy if exists "order_auto_remote_events_select_own" on public.order_auto_remote_events;

create policy "order_auto_remote_events_select_own"
on public.order_auto_remote_events
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

create index if not exists order_auto_contracts_user_updated_idx
on public.order_auto_contracts (user_id, updated_at desc);

create index if not exists order_auto_remote_contracts_owner_updated_idx
on public.order_auto_remote_contracts (owner_user_id, updated_at desc);

create index if not exists order_auto_remote_contracts_contract_idx
on public.order_auto_remote_contracts (contract_id, created_at desc);

create index if not exists order_auto_remote_events_owner_created_idx
on public.order_auto_remote_events (owner_user_id, created_at desc);

create or replace function public.create_order_auto_remote_contract(
  p_contract_id text,
  p_access_token text,
  p_passcode text,
  p_expires_at timestamptz
)
returns table(remote_id uuid, expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_contract public.order_auto_contracts%rowtype;
  v_remote public.order_auto_remote_contracts%rowtype;
begin
  if v_user_id is null then
    return;
  end if;
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return;
  end if;
  if p_expires_at is null
    or p_expires_at <= now()
    or p_expires_at > now() + interval '30 days' then
    return;
  end if;

  select * into v_contract
  from public.order_auto_contracts
  where id = p_contract_id and user_id = v_user_id;

  if not found then
    return;
  end if;

  update public.order_auto_remote_contracts
  set status = '取消'
  where contract_id = p_contract_id
    and owner_user_id = v_user_id
    and status in ('送信済み', '開封済み');

  insert into public.order_auto_remote_contracts (
    contract_id,
    owner_user_id,
    access_token_hash,
    passcode_hash,
    contract_data,
    expires_at
  ) values (
    p_contract_id,
    v_user_id,
    extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256'),
    extensions.crypt(p_passcode, extensions.gen_salt('bf', 10)),
    v_contract.data,
    p_expires_at
  ) returning * into v_remote;

  update public.order_auto_contracts
  set
    status = '送信済み',
    data = jsonb_set(v_contract.data, '{remoteStatus}', '"送信済み"'::jsonb, true)
  where id = p_contract_id and user_id = v_user_id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type
  ) values (
    v_remote.id,
    v_user_id,
    'created'
  );

  return query select v_remote.id, v_remote.expires_at;
end;
$$;

create or replace function public.read_order_auto_remote_contract(
  p_access_token text,
  p_passcode text
)
returns table(
  remote_id uuid,
  contract_id text,
  contract_data jsonb,
  expires_at timestamptz,
  status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_remote public.order_auto_remote_contracts%rowtype;
  v_now timestamptz := now();
  v_failed_attempts integer;
begin
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return;
  end if;

  select * into v_remote
  from public.order_auto_remote_contracts
  where access_token_hash = extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256')
  for update;

  if not found
    or v_remote.status in ('完了', '取消')
    or v_remote.expires_at <= v_now
    or (v_remote.locked_until is not null and v_remote.locked_until > v_now) then
    return;
  end if;

  if extensions.crypt(p_passcode, v_remote.passcode_hash) <> v_remote.passcode_hash then
    v_failed_attempts := v_remote.failed_attempts + 1;
    update public.order_auto_remote_contracts
    set
      failed_attempts = v_failed_attempts,
      locked_until = case when v_failed_attempts >= 5 then v_now + interval '15 minutes' else null end
    where id = v_remote.id;

    insert into public.order_auto_remote_events (
      remote_contract_id,
      owner_user_id,
      event_type,
      metadata
    ) values (
      v_remote.id,
      v_remote.owner_user_id,
      'unlock_failed',
      jsonb_build_object('failed_attempts', v_failed_attempts)
    );
    return;
  end if;

  update public.order_auto_remote_contracts
  set
    status = '開封済み',
    opened_at = coalesce(opened_at, v_now),
    failed_attempts = 0,
    locked_until = null
  where id = v_remote.id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type
  ) values (
    v_remote.id,
    v_remote.owner_user_id,
    'opened'
  );

  return query
  select v_remote.id, v_remote.contract_id, v_remote.contract_data, v_remote.expires_at, '開封済み'::text;
end;
$$;

create or replace function public.complete_order_auto_remote_contract(
  p_access_token text,
  p_passcode text,
  p_signer_name text,
  p_consent_items jsonb,
  p_signature_data_url text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_remote public.order_auto_remote_contracts%rowtype;
  v_now timestamptz := now();
  v_clean_name text := btrim(p_signer_name);
begin
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return false;
  end if;
  if v_clean_name is null or length(v_clean_name) < 1 or length(v_clean_name) > 120 then
    return false;
  end if;
  if p_consent_items is null
    or jsonb_typeof(p_consent_items) <> 'array'
    or jsonb_array_length(p_consent_items) < 1 then
    return false;
  end if;
  if p_signature_data_url is null
    or p_signature_data_url !~ '^data:image/png;base64,'
    or octet_length(p_signature_data_url) > 750000 then
    return false;
  end if;

  select * into v_remote
  from public.order_auto_remote_contracts
  where access_token_hash = extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256')
  for update;

  if not found
    or v_remote.status in ('完了', '取消')
    or v_remote.expires_at <= v_now
    or (v_remote.locked_until is not null and v_remote.locked_until > v_now)
    or extensions.crypt(p_passcode, v_remote.passcode_hash) <> v_remote.passcode_hash then
    return false;
  end if;

  update public.order_auto_remote_contracts
  set
    status = '完了',
    signer_name = v_clean_name,
    consent_items = p_consent_items,
    signature_data_url = p_signature_data_url,
    completed_at = v_now,
    failed_attempts = 0,
    locked_until = null
  where id = v_remote.id;

  update public.order_auto_contracts
  set
    status = '完了',
    completed_at = v_now,
    data = jsonb_set(
      jsonb_set(data, '{contractStatus}', '"完了"'::jsonb, true),
      '{remoteStatus}',
      '"完了"'::jsonb,
      true
    )
  where id = v_remote.contract_id and user_id = v_remote.owner_user_id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type,
    metadata
  ) values (
    v_remote.id,
    v_remote.owner_user_id,
    'completed',
    jsonb_build_object('signer_name', v_clean_name)
  );

  return true;
end;
$$;

revoke all privileges on table public.order_auto_contracts from anon, authenticated;
revoke all privileges on table public.order_auto_remote_contracts from anon, authenticated;
revoke all privileges on table public.order_auto_remote_events from anon, authenticated;

grant select, insert, update, delete on table public.order_auto_contracts to authenticated;
grant select, delete on table public.order_auto_remote_contracts to authenticated;
grant select on table public.order_auto_remote_events to authenticated;

revoke all privileges on function public.set_order_auto_updated_at() from public, anon, authenticated;
revoke all privileges on function public.create_order_auto_remote_contract(text, text, text, timestamptz) from public, anon, authenticated;
revoke all privileges on function public.read_order_auto_remote_contract(text, text) from public, anon, authenticated;
revoke all privileges on function public.complete_order_auto_remote_contract(text, text, text, jsonb, text) from public, anon, authenticated;

grant execute on function public.create_order_auto_remote_contract(text, text, text, timestamptz) to authenticated;
grant execute on function public.read_order_auto_remote_contract(text, text) to anon, authenticated;
grant execute on function public.complete_order_auto_remote_contract(text, text, text, jsonb, text) to anon, authenticated;
